export enum MEMBERSHIP_DURATION {
  ONE_MONTH = 'ONE_MONTH',
  THREE_MONTHS = 'THREE_MONTHS',
  ONE_YEAR = 'ONE_YEAR',
}
export const MEMBERSHIP_PRICE = {
  ONE_MONTH: 29,
  THREE_MONTHS: 59,
  ONE_YEAR: 199,
};
export const PAYMENT_RECIPIENT =
  process.env.NEXT_PUBLIC_SOLANA_PAYMENT_RECIPIENT_ADDRESS ||
  'pace8vZSciSoFhSZJ685YipGPbstTH7FYnrjFMZpjfM';
export const USDC_MAINNET = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
export const USDC_DEVNET = '4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU';
